// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy6F9Qf894I1-LiOv-yBaS7Tfc6sJvo9w',
    appId: '1:23435174186:android:d5930796711c102d6ffe53',
    messagingSenderId: '23435174186',
    projectId: 'event-app-29c1e',
    storageBucket: 'event-app-29c1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfziqW5BB5cb7ORMEKEz_-IMOJG4PjJko',
    appId: '1:23435174186:ios:ce1995730236c86a6ffe53',
    messagingSenderId: '23435174186',
    projectId: 'event-app-29c1e',
    storageBucket: 'event-app-29c1e.appspot.com',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0cosdGsQZl4-p05ISiQyxoVHijYIKz44',
    appId: '1:23435174186:web:505d6e8d925e8c616ffe53',
    messagingSenderId: '23435174186',
    projectId: 'event-app-29c1e',
    authDomain: 'event-app-29c1e.firebaseapp.com',
    storageBucket: 'event-app-29c1e.appspot.com',
    measurementId: 'G-7P9BL1L59V',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfziqW5BB5cb7ORMEKEz_-IMOJG4PjJko',
    appId: '1:23435174186:ios:ce1995730236c86a6ffe53',
    messagingSenderId: '23435174186',
    projectId: 'event-app-29c1e',
    storageBucket: 'event-app-29c1e.appspot.com',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0cosdGsQZl4-p05ISiQyxoVHijYIKz44',
    appId: '1:23435174186:web:349f3061cb3f44486ffe53',
    messagingSenderId: '23435174186',
    projectId: 'event-app-29c1e',
    authDomain: 'event-app-29c1e.firebaseapp.com',
    storageBucket: 'event-app-29c1e.appspot.com',
    measurementId: 'G-X5T2W8G0PY',
  );

}